# LeeesBungeeQueue V4.1.5
# Make the main server the default one you login to
# and then it should work if it doesnt add me on discord for help
# my discord is Leee#9594 add to ask any questions
# READ ME: all colours are orange by default just add & and colour
# to change the colours to your liking

#Username regex
REGEX: "[a-zA-Z0-9_]*"

#Server is full message
SERVERISFULLMESSAGE: "&67b7t is full"


#Position in queue message by default only sends in chat every 10 seconds
#you can have it on the hotbar by setting POSITIONMESSAGEHOTBAR: "false" to true
POSITIONMESSAGEHOTBAR: "false"
QUEUEPOSITION: "&6Position in queue: &l<position>"
ENABLEKICKMESSAGE: "false"
KICKMESSAGE: "&6You have lost connection to the server"
SERVERDOWNKICKMESSAGE: "&b7b&37t &6is down please try again later :("
#set this to false if you want it to kick players from the
#server when the main server goes down
#if its set to true itll pause the queue and let players
#rejoin and wait in queue until the main server is online
CONNECTTOQUEUEWHENDOWN: "true"

#this shows the queue size when you hover over the ping on the server list
SERVERPINGINFOENABLE: "true"
SERVERPINGINFO:
  - "&b7b&37t &6Queue Info"
  - "&6Priority: &l%priority%"
  - "&6Regular: &l%regular%"
  - "&6Total in queue: &l%totalinqueue%"
  - "&6Max players: &l%maxplayers%"
CUSTOMPROTOCOL: "&b7b&37t &61.8.x to 1.16.x"
ENABLEMOTD: "true"
MOTD: "&b7b&37t &6Queue Size: Prio: &l%priosize% &6Reg: &l%regsize% &6Total: &l%total% &6Max: &l%maxplayers%"
ENABLERANDOMMOTD: "true"
RANDOMMOTDS:
  - "&b7b&37t &6LICK MY BALLS Regular: &l%regsize%"
  - "&b7b&37t &6fuck you cunt Priority: &l%priosize%"
  - "&b7b&37t &6suck my cock"
  - "&b7b&37t &6Infinium on Top"
  - "&b7b&37t &6@Leee Ping hurts please add a ping role choice ;-;"
  - "&b7b&37t &6penis equals happiness"
  - "&b7b&37t &6defiance on top"
  - "&b7b&37t &6tough can be tough"
  - "&b7b&37t &6I support child labour"
  - "&b7b&37t &6ur a pedo"
  - "&b7b&37t &6OVH stands for OVerHeating"
  - "&b7b&37t &6Bro why is my ca Dogwater"
  - "&b7b&37t &6look behind you"
  - "&b7b&37t &6i invest in bitcoin to buy mcchicken"
  - "&b7b&37t &6Kionononononononononononon2"
  - "&b7b&37t &6Snow fear? more like Drink Beer"
  - "&b7b&37t &6FireWork Team X RCP On Top!"
  - "&b7b&37t &6Max is Ninja buaaaa"
  - "&b7b&37t &6i diagnose you with gay"
  - "&b7b&37t &6taco taco taco taco taco"
  - "&b7b&37t &6taco taco taco fireWORK"
  - "&b7b&37t &6leee is my senpai"
  - "&b7b&37t &6fuck legion"
  - "&b7b&37t &6LEEE IF YOU SEE THIS JOIN THE CALL. BoonoBoi, Cubebuilder, 254n-m"
  - "&b7b&37t &6254n_m Hes a god."
  - "&b7b&37t &6error"
  - "&b7b&37t &6you are perminantly banned from this server"
  - "&b7b&37t &6Wait i can talk if i just do this ? @Leee"
  - "&b7b&37t &a&lIMPERIUM ANTI &4&lNEWFAGS"
  - "&b7b&37t &6that is very poggers"
  - "&b7b&37t &6fuck you"
  - "&b7b&37t &ataco Taco taco taco FireWORK Team On Top!"
  - "&b7b&37t &6Leee is a God"
  - "&b7b&37t &61589299 2578404 is my stash"
  - "&b7b&37t &6I own you and all"
  - "&b7b&37t &6dont join!!! Your base was griefed!!! Ull be sad!!!"
  - "&b7b&37t &6lmao u mad?"
  - "&b7b&37t &6no you has been backdoored"
  - "&b7b&37t &6piko pal k lee"
  - "&b7b&37t &6cat is gay"
  - "&b7b&37t &6there is a pickle way too fucking deep in someones ass right now."
  - "&b7b&37t &6this server has been blacklisted by Mojang."
  - "&b7b&37t &6eggfruit"
  - "&b7b&37t &6Free kits at 0 0!"
  - "&b7b&37t &6blizzard owns u"
  - "&b7b&37t &632ks at 0 0!"
  - "&b7b&37t &6illigals at 16882827 467782"

#Set the queue servers name that is in the bungee config.yml
#Note that the main server is always the one you login to first
#The main server server is the one that has a queue to protect it
#make sure you set the default server in bungee config.yml correctly
QUEUESERVER: "queue"
MAINSERVER: "7b7t"
#set this to false if your a premium server
ENABLEAUTHSERVER: "true"
AUTHSERVER: "auth"
#server to send the players to after queue
AFTERQUEUE: "auth"


#Connecting to server message use <server> if you want it
#to just use the name of the default server
JOININGMAINSERVER: "&6Connecting to 7b7t..."


#Max players allowed onto main server
MAINSERVERSLOTS: 150

#set this to true if you wanna make the
#max players appear as whatever number you want
ENABLEQUEUESERVERSLOTS: "true"
QUEUESERVERSLOTS: 10000


#Queue move delay in miliseconds default is 2000ms
#please note this only guaranteed to not have issues 2000ms and higher
QUEUEMOVEDELAY: 2000


#this feature is enabled by default
#it puts players in queue when they login
#to prevent mass raids from crashing your main
#server set to false to disable it
ALWAYSQUEUE: "true"


#Permissions
#in order for queue bypass to work any accounts with the permission
#must also not have priority queue if they have both the permissions
#it will confuse them and break the queue
QUEUEBYPASSPERMISSION: "queue.override"
QUEUEPRIORITYPERMISSION: "queue.priority"
ADMINPERMISSION: "queue.admin"


#Queue server tablist configuration use <position> to show the current position of the player
#and use <wait> to show the estimated wait time of t    he player(not very accurate yet)
#this only shows when your in the queue waiting to join use a separate plugin for your main server
HEADER: "\n&b7builders&37tools\n\n&67b7t is full\nPosition in queue: &l<position>\n&6Estimated time: &l<wait>\n"

FOOTER: "\n   &6You can now donate to receive priority queue status, please visit donate.7b7t.me   \n\n&7contact: nate@xera.ca\n
discussion: http://discord.7b7t.me\nwebsite: https://www.7b7t.me\nThese are the only official 7b7t websites and contacts\n"


#configs for priority queue tablist
HEADERPRIORITY: "\n&b7builders&37tools\n\n&67b7t is full\nPosition in queue: &l<position>\n&6Estimated time: &l<wait>\n"

FOOTERPRIORITY: "\n   &6You have priority queue status please wait for an available slot on the server   \n\n&7contact: nate@xera.ca\n
discussion: http://discord.7b7t.me\nwebsite: https://www.7b7t.me\nThese are the only official 7b7t websites and contacts\n"
